/* botsmith.bcs: (Cespenar) */


IF
	Global("C#AjanToB_ItemMaker","GLOBAL",1)
	Global("ImpForgeStuff","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("ImpForgeStuff","GLOBAL",0)
		GiveItemCreate("C#AJSHL3",Player1,0,0,0) // 
		StartDialogueNoSet(Player1)
END

IF
	Global("C#AjanToB_ItemMaker","GLOBAL",2)
	Global("ImpForgeStuff","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("ImpForgeStuff","GLOBAL",0)
		GiveItemCreate("C#AJ012B",Player1,1,3,0) // 
		StartDialogueNoSet(Player1)
END
